services:
  - type: web
    name: sportbooking
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate --noinput && python manage.py collectstatics python create_admin_if_missing.py && gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sportbookingdb
          property: connectionString
databases:
  - name: sportbookingdb
    engine: postgres
    plan: free

