# Generated by Django 5.2.7 on 2025-10-18 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('football', 'Fútbol'), ('tennis', 'Tenis'), ('padel', 'Pádel'), ('basket', 'Baloncesto'), ('racquetball', 'Frontenis'), ('waterpool', 'Piscina')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
            },
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reservation.court')),
            ],
            options={
                'verbose_name': 'Horario de Pista',
                'verbose_name_plural': 'Horarios de Pistas',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('court', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.courtschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-date', 'schedule__start_time'],
                'unique_together': {('date', 'schedule')},
            },
        ),
    ]
