# Generated by Django 5.2.7 on 2025-10-16 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='court',
            options={'verbose_name': 'Pista', 'verbose_name_plural': 'Pistas'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'start_time'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.CharField(choices=[('football', 'Fútbol'), ('tennis', 'Tenis'), ('padel', 'Pádel'), ('basket', 'Baloncesto'), ('racquetball', 'Frontenis'), ('waterpool', 'Piscina')], max_length=20),
        ),
        migrations.CreateModel(
            name='CourtSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='reservation.court')),
            ],
            options={
                'verbose_name': 'Horario de Pista',
                'verbose_name_plural': 'Horarios de Pistas',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('court', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
