# Generated by Django 5.2.7 on 2025-10-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
