# Generated by Django 5.2.7 on 2025-10-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_court_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
    ]
