# Generated by Django 5.2.7 on 2025-10-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
